/**
 * Market definitions and stock universe data.
 * Extracted from App.jsx for maintainability.
 */

export const MARKETS = [
  { id: 'US', name: 'US', flag: '\u{1F1FA}\u{1F1F8}', currency: '$', currencyName: 'USD', defaultSymbol: 'AAPL' },
  { id: 'India', name: 'India', flag: '\u{1F1EE}\u{1F1F3}', currency: '\u20B9', currencyName: 'INR', defaultSymbol: 'RELIANCE.NS' },
  { id: 'UK', name: 'UK', flag: '\u{1F1EC}\u{1F1E7}', currency: '\u00A3', currencyName: 'GBP', defaultSymbol: 'HSBA.L' },
  { id: 'Germany', name: 'Germany', flag: '\u{1F1E9}\u{1F1EA}', currency: '\u20AC', currencyName: 'EUR', defaultSymbol: 'SAP.DE' },
  { id: 'France', name: 'France', flag: '\u{1F1EB}\u{1F1F7}', currency: '\u20AC', currencyName: 'EUR', defaultSymbol: 'OR.PA' },
  { id: 'Japan', name: 'Japan', flag: '\u{1F1EF}\u{1F1F5}', currency: '\u00A5', currencyName: 'JPY', defaultSymbol: '7203.T' },
  { id: 'China', name: 'China', flag: '\u{1F1E8}\u{1F1F3}', currency: '\u00A5', currencyName: 'CNY', defaultSymbol: '9988.HK' },
  { id: 'HongKong', name: 'Hong Kong', flag: '\u{1F1ED}\u{1F1F0}', currency: 'HK$', currencyName: 'HKD', defaultSymbol: '0700.HK' },
  { id: 'Taiwan', name: 'Taiwan', flag: '\u{1F1F9}\u{1F1FC}', currency: 'NT$', currencyName: 'TWD', defaultSymbol: '2330.TW' },
  { id: 'Australia', name: 'Australia', flag: '\u{1F1E6}\u{1F1FA}', currency: 'A$', currencyName: 'AUD', defaultSymbol: 'BHP.AX' },
  { id: 'Canada', name: 'Canada', flag: '\u{1F1E8}\u{1F1E6}', currency: 'C$', currencyName: 'CAD', defaultSymbol: 'RY.TO' },
  { id: 'Brazil', name: 'Brazil', flag: '\u{1F1E7}\u{1F1F7}', currency: 'R$', currencyName: 'BRL', defaultSymbol: 'PETR4.SA' },
  { id: 'Korea', name: 'Korea', flag: '\u{1F1F0}\u{1F1F7}', currency: '\u20A9', currencyName: 'KRW', defaultSymbol: '005930.KS' },
  { id: 'Singapore', name: 'Singapore', flag: '\u{1F1F8}\u{1F1EC}', currency: 'S$', currencyName: 'SGD', defaultSymbol: 'D05.SI' },
  { id: 'Switzerland', name: 'Switzerland', flag: '\u{1F1E8}\u{1F1ED}', currency: 'CHF', currencyName: 'CHF', defaultSymbol: 'NESN.SW' },
  { id: 'Netherlands', name: 'Netherlands', flag: '\u{1F1F3}\u{1F1F1}', currency: '\u20AC', currencyName: 'EUR', defaultSymbol: 'ASML.AS' },
  { id: 'Spain', name: 'Spain', flag: '\u{1F1EA}\u{1F1F8}', currency: '\u20AC', currencyName: 'EUR', defaultSymbol: 'SAN.MC' },
  { id: 'Italy', name: 'Italy', flag: '\u{1F1EE}\u{1F1F9}', currency: '\u20AC', currencyName: 'EUR', defaultSymbol: 'ENI.MI' },
  { id: 'Crypto', name: 'Crypto', flag: '\u20BF', currency: '$', currencyName: 'USD', defaultSymbol: 'BTC-USD' },
  { id: 'ETF', name: 'ETF', flag: '\u{1F4CA}', currency: '$', currencyName: 'USD', defaultSymbol: 'SPY' },
  { id: 'Forex', name: 'Forex', flag: '\u{1F4B1}', currency: '$', currencyName: 'USD', defaultSymbol: 'EURUSD=X' },
  { id: 'Commodities', name: 'Commodities', flag: '\u{1F6E2}\uFE0F', currency: '$', currencyName: 'USD', defaultSymbol: 'GC=F' },
];

export const STATIC_UNIVERSE = {
  'US Tech': [
    { symbol: 'AAPL', name: 'Apple', flag: '\u{1F1FA}\u{1F1F8}', currency: '$' },
    { symbol: 'MSFT', name: 'Microsoft', flag: '\u{1F1FA}\u{1F1F8}', currency: '$' },
    { symbol: 'GOOGL', name: 'Alphabet', flag: '\u{1F1FA}\u{1F1F8}', currency: '$' },
    { symbol: 'NVDA', name: 'NVIDIA', flag: '\u{1F1FA}\u{1F1F8}', currency: '$' },
    { symbol: 'TSLA', name: 'Tesla', flag: '\u{1F1FA}\u{1F1F8}', currency: '$' },
    { symbol: 'META', name: 'Meta', flag: '\u{1F1FA}\u{1F1F8}', currency: '$' },
    { symbol: 'AMZN', name: 'Amazon', flag: '\u{1F1FA}\u{1F1F8}', currency: '$' },
    { symbol: 'AMD', name: 'AMD', flag: '\u{1F1FA}\u{1F1F8}', currency: '$' },
  ],
  'India': [
    { symbol: 'RELIANCE.NS', name: 'Reliance', flag: '\u{1F1EE}\u{1F1F3}', currency: '\u20B9' },
    { symbol: 'TCS.NS', name: 'TCS', flag: '\u{1F1EE}\u{1F1F3}', currency: '\u20B9' },
    { symbol: 'HDFCBANK.NS', name: 'HDFC Bank', flag: '\u{1F1EE}\u{1F1F3}', currency: '\u20B9' },
    { symbol: 'INFY.NS', name: 'Infosys', flag: '\u{1F1EE}\u{1F1F3}', currency: '\u20B9' },
    { symbol: 'ICICIBANK.NS', name: 'ICICI Bank', flag: '\u{1F1EE}\u{1F1F3}', currency: '\u20B9' },
    { symbol: 'HINDUNILVR.NS', name: 'HUL', flag: '\u{1F1EE}\u{1F1F3}', currency: '\u20B9' },
  ],
  'UK': [
    { symbol: 'HSBA.L', name: 'HSBC', flag: '\u{1F1EC}\u{1F1E7}', currency: '\u00A3' },
    { symbol: 'BP.L', name: 'BP', flag: '\u{1F1EC}\u{1F1E7}', currency: '\u00A3' },
    { symbol: 'SHEL.L', name: 'Shell', flag: '\u{1F1EC}\u{1F1E7}', currency: '\u00A3' },
    { symbol: 'AZN.L', name: 'AstraZeneca', flag: '\u{1F1EC}\u{1F1E7}', currency: '\u00A3' },
    { symbol: 'GSK.L', name: 'GSK', flag: '\u{1F1EC}\u{1F1E7}', currency: '\u00A3' },
  ],
  'Germany': [
    { symbol: 'SAP.DE', name: 'SAP', flag: '\u{1F1E9}\u{1F1EA}', currency: '\u20AC' },
    { symbol: 'SIE.DE', name: 'Siemens', flag: '\u{1F1E9}\u{1F1EA}', currency: '\u20AC' },
    { symbol: 'ALV.DE', name: 'Allianz', flag: '\u{1F1E9}\u{1F1EA}', currency: '\u20AC' },
    { symbol: 'DTE.DE', name: 'Deutsche Telekom', flag: '\u{1F1E9}\u{1F1EA}', currency: '\u20AC' },
  ],
  'France': [
    { symbol: 'OR.PA', name: "L'Oreal", flag: '\u{1F1EB}\u{1F1F7}', currency: '\u20AC' },
    { symbol: 'MC.PA', name: 'LVMH', flag: '\u{1F1EB}\u{1F1F7}', currency: '\u20AC' },
    { symbol: 'TTE.PA', name: 'TotalEnergies', flag: '\u{1F1EB}\u{1F1F7}', currency: '\u20AC' },
    { symbol: 'SAN.PA', name: 'Sanofi', flag: '\u{1F1EB}\u{1F1F7}', currency: '\u20AC' },
  ],
  'Japan': [
    { symbol: '7203.T', name: 'Toyota', flag: '\u{1F1EF}\u{1F1F5}', currency: '\u00A5' },
    { symbol: '6758.T', name: 'Sony', flag: '\u{1F1EF}\u{1F1F5}', currency: '\u00A5' },
    { symbol: '9984.T', name: 'SoftBank', flag: '\u{1F1EF}\u{1F1F5}', currency: '\u00A5' },
    { symbol: '6861.T', name: 'Keyence', flag: '\u{1F1EF}\u{1F1F5}', currency: '\u00A5' },
  ],
  'China': [
    { symbol: '9988.HK', name: 'Alibaba', flag: '\u{1F1E8}\u{1F1F3}', currency: 'HK$' },
    { symbol: '9618.HK', name: 'JD.com', flag: '\u{1F1E8}\u{1F1F3}', currency: 'HK$' },
    { symbol: '3690.HK', name: 'Meituan', flag: '\u{1F1E8}\u{1F1F3}', currency: 'HK$' },
    { symbol: '1810.HK', name: 'Xiaomi', flag: '\u{1F1E8}\u{1F1F3}', currency: 'HK$' },
  ],
  'Hong Kong': [
    { symbol: '0700.HK', name: 'Tencent', flag: '\u{1F1ED}\u{1F1F0}', currency: 'HK$' },
    { symbol: '0005.HK', name: 'HSBC HK', flag: '\u{1F1ED}\u{1F1F0}', currency: 'HK$' },
    { symbol: '1299.HK', name: 'AIA Group', flag: '\u{1F1ED}\u{1F1F0}', currency: 'HK$' },
    { symbol: '0941.HK', name: 'China Mobile', flag: '\u{1F1ED}\u{1F1F0}', currency: 'HK$' },
  ],
  'Taiwan': [
    { symbol: '2330.TW', name: 'TSMC', flag: '\u{1F1F9}\u{1F1FC}', currency: 'NT$' },
    { symbol: '2317.TW', name: 'Hon Hai', flag: '\u{1F1F9}\u{1F1FC}', currency: 'NT$' },
    { symbol: '2454.TW', name: 'MediaTek', flag: '\u{1F1F9}\u{1F1FC}', currency: 'NT$' },
    { symbol: '2308.TW', name: 'Delta Electronics', flag: '\u{1F1F9}\u{1F1FC}', currency: 'NT$' },
  ],
  'Australia': [
    { symbol: 'BHP.AX', name: 'BHP', flag: '\u{1F1E6}\u{1F1FA}', currency: 'A$' },
    { symbol: 'CBA.AX', name: 'CommBank', flag: '\u{1F1E6}\u{1F1FA}', currency: 'A$' },
    { symbol: 'CSL.AX', name: 'CSL', flag: '\u{1F1E6}\u{1F1FA}', currency: 'A$' },
    { symbol: 'NAB.AX', name: 'NAB', flag: '\u{1F1E6}\u{1F1FA}', currency: 'A$' },
  ],
  'Canada': [
    { symbol: 'RY.TO', name: 'Royal Bank', flag: '\u{1F1E8}\u{1F1E6}', currency: 'C$' },
    { symbol: 'TD.TO', name: 'TD Bank', flag: '\u{1F1E8}\u{1F1E6}', currency: 'C$' },
    { symbol: 'SHOP.TO', name: 'Shopify', flag: '\u{1F1E8}\u{1F1E6}', currency: 'C$' },
    { symbol: 'ENB.TO', name: 'Enbridge', flag: '\u{1F1E8}\u{1F1E6}', currency: 'C$' },
  ],
  'Brazil': [
    { symbol: 'PETR4.SA', name: 'Petrobras', flag: '\u{1F1E7}\u{1F1F7}', currency: 'R$' },
    { symbol: 'VALE3.SA', name: 'Vale', flag: '\u{1F1E7}\u{1F1F7}', currency: 'R$' },
    { symbol: 'ITUB4.SA', name: 'Itau', flag: '\u{1F1E7}\u{1F1F7}', currency: 'R$' },
    { symbol: 'BBDC4.SA', name: 'Bradesco', flag: '\u{1F1E7}\u{1F1F7}', currency: 'R$' },
  ],
  'Korea': [
    { symbol: '005930.KS', name: 'Samsung', flag: '\u{1F1F0}\u{1F1F7}', currency: '\u20A9' },
    { symbol: '000660.KS', name: 'SK Hynix', flag: '\u{1F1F0}\u{1F1F7}', currency: '\u20A9' },
    { symbol: '035420.KS', name: 'Naver', flag: '\u{1F1F0}\u{1F1F7}', currency: '\u20A9' },
    { symbol: '051910.KS', name: 'LG Chem', flag: '\u{1F1F0}\u{1F1F7}', currency: '\u20A9' },
  ],
  'Singapore': [
    { symbol: 'D05.SI', name: 'DBS', flag: '\u{1F1F8}\u{1F1EC}', currency: 'S$' },
    { symbol: 'O39.SI', name: 'OCBC', flag: '\u{1F1F8}\u{1F1EC}', currency: 'S$' },
    { symbol: 'U11.SI', name: 'UOB', flag: '\u{1F1F8}\u{1F1EC}', currency: 'S$' },
    { symbol: 'Z74.SI', name: 'Singtel', flag: '\u{1F1F8}\u{1F1EC}', currency: 'S$' },
  ],
  'Switzerland': [
    { symbol: 'NESN.SW', name: 'Nestle', flag: '\u{1F1E8}\u{1F1ED}', currency: 'CHF' },
    { symbol: 'ROG.SW', name: 'Roche', flag: '\u{1F1E8}\u{1F1ED}', currency: 'CHF' },
    { symbol: 'NOVN.SW', name: 'Novartis', flag: '\u{1F1E8}\u{1F1ED}', currency: 'CHF' },
    { symbol: 'UBSG.SW', name: 'UBS', flag: '\u{1F1E8}\u{1F1ED}', currency: 'CHF' },
  ],
  'Netherlands': [
    { symbol: 'ASML.AS', name: 'ASML', flag: '\u{1F1F3}\u{1F1F1}', currency: '\u20AC' },
    { symbol: 'INGA.AS', name: 'ING', flag: '\u{1F1F3}\u{1F1F1}', currency: '\u20AC' },
    { symbol: 'PHIA.AS', name: 'Philips', flag: '\u{1F1F3}\u{1F1F1}', currency: '\u20AC' },
    { symbol: 'UNA.AS', name: 'Unilever', flag: '\u{1F1F3}\u{1F1F1}', currency: '\u20AC' },
  ],
  'Spain': [
    { symbol: 'SAN.MC', name: 'Santander', flag: '\u{1F1EA}\u{1F1F8}', currency: '\u20AC' },
    { symbol: 'IBE.MC', name: 'Iberdrola', flag: '\u{1F1EA}\u{1F1F8}', currency: '\u20AC' },
    { symbol: 'ITX.MC', name: 'Inditex', flag: '\u{1F1EA}\u{1F1F8}', currency: '\u20AC' },
    { symbol: 'BBVA.MC', name: 'BBVA', flag: '\u{1F1EA}\u{1F1F8}', currency: '\u20AC' },
  ],
  'Italy': [
    { symbol: 'ENI.MI', name: 'ENI', flag: '\u{1F1EE}\u{1F1F9}', currency: '\u20AC' },
    { symbol: 'ENEL.MI', name: 'Enel', flag: '\u{1F1EE}\u{1F1F9}', currency: '\u20AC' },
    { symbol: 'ISP.MI', name: 'Intesa', flag: '\u{1F1EE}\u{1F1F9}', currency: '\u20AC' },
    { symbol: 'UCG.MI', name: 'UniCredit', flag: '\u{1F1EE}\u{1F1F9}', currency: '\u20AC' },
  ],
  'Crypto': [
    { symbol: 'BTC-USD', name: 'Bitcoin', flag: '\u20BF', currency: '$' },
    { symbol: 'ETH-USD', name: 'Ethereum', flag: '\u039E', currency: '$' },
    { symbol: 'SOL-USD', name: 'Solana', flag: '\u25CE', currency: '$' },
    { symbol: 'XRP-USD', name: 'Ripple', flag: '\u2715', currency: '$' },
    { symbol: 'BNB-USD', name: 'Binance', flag: '\u{1F536}', currency: '$' },
  ],
  'ETF': [
    { symbol: 'SPY', name: 'S&P 500', flag: '\u{1F4CA}', currency: '$' },
    { symbol: 'QQQ', name: 'Nasdaq 100', flag: '\u{1F4CA}', currency: '$' },
    { symbol: 'IWM', name: 'Russell 2000', flag: '\u{1F4CA}', currency: '$' },
    { symbol: 'GLD', name: 'Gold ETF', flag: '\u{1F4CA}', currency: '$' },
    { symbol: 'VTI', name: 'Total Stock', flag: '\u{1F4CA}', currency: '$' },
  ],
  'Forex': [
    { symbol: 'EURUSD=X', name: 'EUR/USD', flag: '\u{1F4B1}', currency: '$' },
    { symbol: 'GBPUSD=X', name: 'GBP/USD', flag: '\u{1F4B1}', currency: '$' },
    { symbol: 'USDJPY=X', name: 'USD/JPY', flag: '\u{1F4B1}', currency: '\u00A5' },
    { symbol: 'AUDUSD=X', name: 'AUD/USD', flag: '\u{1F4B1}', currency: '$' },
  ],
  'Commodities': [
    { symbol: 'GC=F', name: 'Gold', flag: '\u{1F947}', currency: '$' },
    { symbol: 'SI=F', name: 'Silver', flag: '\u{1F948}', currency: '$' },
    { symbol: 'CL=F', name: 'Crude Oil', flag: '\u{1F6E2}\uFE0F', currency: '$' },
    { symbol: 'NG=F', name: 'Natural Gas', flag: '\u{1F525}', currency: '$' },
  ],
};

export const MARKET_MOVERS = {
  'US': ['AAPL', 'MSFT', 'NVDA', 'TSLA', 'AMD', 'META'],
  'India': ['RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS'],
  'UK': ['HSBA.L', 'BP.L', 'SHEL.L', 'AZN.L'],
  'Germany': ['SAP.DE', 'SIE.DE', 'VOW3.DE', 'BMW.DE'],
  'France': ['OR.PA', 'MC.PA', 'AIR.PA', 'TTE.PA'],
  'Japan': ['7203.T', '6758.T', '9984.T', '7974.T'],
  'China': ['9988.HK', '0700.HK', '3690.HK', '9618.HK'],
  'HongKong': ['0700.HK', '9988.HK', '0005.HK', '0388.HK'],
  'Taiwan': ['2330.TW', '2317.TW', '2454.TW', '2308.TW'],
  'Australia': ['BHP.AX', 'CBA.AX', 'CSL.AX', 'NAB.AX'],
  'Canada': ['RY.TO', 'TD.TO', 'ENB.TO', 'SHOP.TO'],
  'Brazil': ['PETR4.SA', 'VALE3.SA', 'ITUB4.SA', 'ABEV3.SA'],
  'Korea': ['005930.KS', '000660.KS', '035420.KS'],
  'Singapore': ['D05.SI', 'O39.SI', 'U11.SI'],
  'Switzerland': ['NESN.SW', 'NOVN.SW', 'ROG.SW', 'UBSG.SW'],
  'Netherlands': ['ASML.AS', 'INGA.AS', 'PHIA.AS', 'ADYEN.AS'],
  'Spain': ['SAN.MC', 'BBVA.MC', 'ITX.MC', 'IBE.MC'],
  'Italy': ['ENI.MI', 'ENEL.MI', 'ISP.MI', 'RACE.MI'],
  'Crypto': ['BTC-USD', 'ETH-USD', 'SOL-USD', 'XRP-USD'],
  'ETF': ['SPY', 'QQQ', 'IWM', 'DIA'],
  'Commodities': ['GC=F', 'CL=F', 'SI=F', 'NG=F'],
  'Forex': ['EURUSD=X', 'GBPUSD=X', 'USDJPY=X', 'AUDUSD=X'],
};
