/**
 * Symbol search index — used for autocomplete in the search bar.
 * Covers NSE Nifty 50, additional NSE stocks, and key global markets.
 * To add a new symbol: verify ticker at nseindia.com (for .NS) then append here.
 */

export const SYMBOL_INDEX = [
  // ── NSE India — Nifty 50 ────────────────────────────────────────────────────
  { symbol: 'RELIANCE.NS', name: 'Reliance Industries', market: 'India', sector: 'Energy' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services', market: 'India', sector: 'IT' },
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank', market: 'India', sector: 'Banking' },
  { symbol: 'INFY.NS', name: 'Infosys', market: 'India', sector: 'IT' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank', market: 'India', sector: 'Banking' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever', market: 'India', sector: 'FMCG' },
  { symbol: 'ITC.NS', name: 'ITC', market: 'India', sector: 'FMCG' },
  { symbol: 'SBIN.NS', name: 'State Bank of India', market: 'India', sector: 'Banking' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel', market: 'India', sector: 'Telecom' },
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance', market: 'India', sector: 'NBFC' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank', market: 'India', sector: 'Banking' },
  { symbol: 'LT.NS', name: 'Larsen & Toubro', market: 'India', sector: 'Infra' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints', market: 'India', sector: 'Paints' },
  { symbol: 'AXISBANK.NS', name: 'Axis Bank', market: 'India', sector: 'Banking' },
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki', market: 'India', sector: 'Auto' },
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharmaceutical', market: 'India', sector: 'Pharma' },
  { symbol: 'TITAN.NS', name: 'Titan Company', market: 'India', sector: 'Consumer' },
  { symbol: 'WIPRO.NS', name: 'Wipro', market: 'India', sector: 'IT' },
  { symbol: 'NTPC.NS', name: 'NTPC', market: 'India', sector: 'Power' },
  { symbol: 'POWERGRID.NS', name: 'Power Grid Corporation', market: 'India', sector: 'Power' },
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement', market: 'India', sector: 'Cement' },
  { symbol: 'NESTLEIND.NS', name: 'Nestle India', market: 'India', sector: 'FMCG' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors', market: 'India', sector: 'Auto' },
  { symbol: 'TECHM.NS', name: 'Tech Mahindra', market: 'India', sector: 'IT' },
  { symbol: 'HCLTECH.NS', name: 'HCL Technologies', market: 'India', sector: 'IT' },
  { symbol: 'TATASTEEL.NS', name: 'Tata Steel', market: 'India', sector: 'Metals' },
  { symbol: 'JSWSTEEL.NS', name: 'JSW Steel', market: 'India', sector: 'Metals' },
  { symbol: 'ONGC.NS', name: 'ONGC', market: 'India', sector: 'Energy' },
  { symbol: 'DRREDDY.NS', name: "Dr. Reddy's Laboratories", market: 'India', sector: 'Pharma' },
  { symbol: 'CIPLA.NS', name: 'Cipla', market: 'India', sector: 'Pharma' },
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports', market: 'India', sector: 'Logistics' },
  { symbol: 'GRASIM.NS', name: 'Grasim Industries', market: 'India', sector: 'Cement' },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp', market: 'India', sector: 'Auto' },
  { symbol: 'EICHERMOT.NS', name: 'Eicher Motors', market: 'India', sector: 'Auto' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv', market: 'India', sector: 'NBFC' },
  { symbol: 'TATACONSUM.NS', name: 'Tata Consumer Products', market: 'India', sector: 'FMCG' },
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals', market: 'India', sector: 'Healthcare' },
  { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank', market: 'India', sector: 'Banking' },
  { symbol: 'BPCL.NS', name: 'BPCL', market: 'India', sector: 'Energy' },
  { symbol: 'COALINDIA.NS', name: 'Coal India', market: 'India', sector: 'Mining' },
  { symbol: 'SHRIRAMFIN.NS', name: 'Shriram Finance', market: 'India', sector: 'NBFC' },
  { symbol: 'BRITANNIA.NS', name: 'Britannia Industries', market: 'India', sector: 'FMCG' },
  { symbol: 'DIVISLAB.NS', name: "Divi's Laboratories", market: 'India', sector: 'Pharma' },
  { symbol: 'HDFCLIFE.NS', name: 'HDFC Life Insurance', market: 'India', sector: 'Insurance' },
  { symbol: 'SBILIFE.NS', name: 'SBI Life Insurance', market: 'India', sector: 'Insurance' },
  { symbol: 'M&M.NS', name: 'Mahindra & Mahindra', market: 'India', sector: 'Auto' },
  { symbol: 'HINDALCO.NS', name: 'Hindalco Industries', market: 'India', sector: 'Metals' },
  // ── NSE — Defence / PSU / Mid-cap ───────────────────────────────────────────
  { symbol: 'BEL.NS', name: 'Bharat Electronics', market: 'India', sector: 'Defence' },
  { symbol: 'HAL.NS', name: 'Hindustan Aeronautics (HAL)', market: 'India', sector: 'Defence' },
  { symbol: 'BHEL.NS', name: 'Bharat Heavy Electricals', market: 'India', sector: 'Engineering' },
  { symbol: 'IRFC.NS', name: 'Indian Railway Finance Corp', market: 'India', sector: 'Finance' },
  { symbol: 'PFC.NS', name: 'Power Finance Corporation', market: 'India', sector: 'Finance' },
  { symbol: 'RECLTD.NS', name: 'REC Limited', market: 'India', sector: 'Finance' },
  { symbol: 'IRCTC.NS', name: 'IRCTC', market: 'India', sector: 'Travel' },
  { symbol: 'PIDILITIND.NS', name: 'Pidilite Industries', market: 'India', sector: 'Chemical' },
  { symbol: 'DMART.NS', name: 'DMart (Avenue Supermarts)', market: 'India', sector: 'Retail' },
  { symbol: 'AMBUJACEM.NS', name: 'Ambuja Cements', market: 'India', sector: 'Cement' },
  { symbol: 'BANKBARODA.NS', name: 'Bank of Baroda', market: 'India', sector: 'Banking' },
  { symbol: 'CANBK.NS', name: 'Canara Bank', market: 'India', sector: 'Banking' },
  { symbol: 'PNB.NS', name: 'Punjab National Bank', market: 'India', sector: 'Banking' },
  { symbol: 'ZOMATO.NS', name: 'Zomato', market: 'India', sector: 'Tech' },
  { symbol: 'PAYTM.NS', name: 'Paytm (One97 Communications)', market: 'India', sector: 'Tech' },
  { symbol: 'NYKAA.NS', name: 'Nykaa (FSN E-Commerce)', market: 'India', sector: 'Tech' },
  { symbol: 'TRENT.NS', name: 'Trent (Westside / Zudio)', market: 'India', sector: 'Retail' },
  { symbol: 'MUTHOOTFIN.NS', name: 'Muthoot Finance', market: 'India', sector: 'Finance' },
  { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto', market: 'India', sector: 'Auto' },
  { symbol: 'SOLARINDS.NS', name: 'Solar Industries India', market: 'India', sector: 'Defence' },
  { symbol: 'NHPC.NS', name: 'NHPC', market: 'India', sector: 'Power' },
  { symbol: 'SJVN.NS', name: 'SJVN', market: 'India', sector: 'Power' },
  // ── BSE India — Sensex 30 + popular stocks (.BO) ────────────────────────────
  { symbol: 'RELIANCE.BO', name: 'Reliance Industries (BSE)', market: 'India', sector: 'Energy' },
  { symbol: 'TCS.BO', name: 'Tata Consultancy Services (BSE)', market: 'India', sector: 'IT' },
  { symbol: 'HDFCBANK.BO', name: 'HDFC Bank (BSE)', market: 'India', sector: 'Banking' },
  { symbol: 'INFY.BO', name: 'Infosys (BSE)', market: 'India', sector: 'IT' },
  { symbol: 'ICICIBANK.BO', name: 'ICICI Bank (BSE)', market: 'India', sector: 'Banking' },
  { symbol: 'HINDUNILVR.BO', name: 'Hindustan Unilever (BSE)', market: 'India', sector: 'FMCG' },
  { symbol: 'ITC.BO', name: 'ITC (BSE)', market: 'India', sector: 'FMCG' },
  { symbol: 'SBIN.BO', name: 'State Bank of India (BSE)', market: 'India', sector: 'Banking' },
  { symbol: 'BHARTIARTL.BO', name: 'Bharti Airtel (BSE)', market: 'India', sector: 'Telecom' },
  { symbol: 'BAJFINANCE.BO', name: 'Bajaj Finance (BSE)', market: 'India', sector: 'NBFC' },
  { symbol: 'KOTAKBANK.BO', name: 'Kotak Mahindra Bank (BSE)', market: 'India', sector: 'Banking' },
  { symbol: 'LT.BO', name: 'Larsen & Toubro (BSE)', market: 'India', sector: 'Infra' },
  { symbol: 'AXISBANK.BO', name: 'Axis Bank (BSE)', market: 'India', sector: 'Banking' },
  { symbol: 'MARUTI.BO', name: 'Maruti Suzuki (BSE)', market: 'India', sector: 'Auto' },
  { symbol: 'SUNPHARMA.BO', name: 'Sun Pharmaceutical (BSE)', market: 'India', sector: 'Pharma' },
  { symbol: 'TITAN.BO', name: 'Titan Company (BSE)', market: 'India', sector: 'Consumer' },
  { symbol: 'WIPRO.BO', name: 'Wipro (BSE)', market: 'India', sector: 'IT' },
  { symbol: 'TATAMOTORS.BO', name: 'Tata Motors (BSE)', market: 'India', sector: 'Auto' },
  { symbol: 'HCLTECH.BO', name: 'HCL Technologies (BSE)', market: 'India', sector: 'IT' },
  { symbol: 'TATASTEEL.BO', name: 'Tata Steel (BSE)', market: 'India', sector: 'Metals' },
  { symbol: 'ONGC.BO', name: 'ONGC (BSE)', market: 'India', sector: 'Energy' },
  { symbol: 'BAJAJFINSV.BO', name: 'Bajaj Finserv (BSE)', market: 'India', sector: 'NBFC' },
  { symbol: 'M&M.BO', name: 'Mahindra & Mahindra (BSE)', market: 'India', sector: 'Auto' },
  { symbol: 'ADANIPORTS.BO', name: 'Adani Ports (BSE)', market: 'India', sector: 'Logistics' },
  {
    symbol: 'DRREDDY.BO',
    name: "Dr. Reddy's Laboratories (BSE)",
    market: 'India',
    sector: 'Pharma',
  },
  { symbol: 'CIPLA.BO', name: 'Cipla (BSE)', market: 'India', sector: 'Pharma' },
  { symbol: 'HINDALCO.BO', name: 'Hindalco Industries (BSE)', market: 'India', sector: 'Metals' },
  { symbol: 'ZOMATO.BO', name: 'Zomato (BSE)', market: 'India', sector: 'Tech' },
  { symbol: 'BEL.BO', name: 'Bharat Electronics (BSE)', market: 'India', sector: 'Defence' },
  { symbol: 'HAL.BO', name: 'Hindustan Aeronautics (BSE)', market: 'India', sector: 'Defence' },
  // ── US Tech ─────────────────────────────────────────────────────────────────
  { symbol: 'AAPL', name: 'Apple', market: 'US', sector: 'Tech' },
  { symbol: 'MSFT', name: 'Microsoft', market: 'US', sector: 'Tech' },
  { symbol: 'GOOGL', name: 'Alphabet (Google)', market: 'US', sector: 'Tech' },
  { symbol: 'AMZN', name: 'Amazon', market: 'US', sector: 'Tech' },
  { symbol: 'NVDA', name: 'NVIDIA', market: 'US', sector: 'Tech' },
  { symbol: 'META', name: 'Meta Platforms', market: 'US', sector: 'Tech' },
  { symbol: 'TSLA', name: 'Tesla', market: 'US', sector: 'Auto' },
  { symbol: 'AMD', name: 'AMD', market: 'US', sector: 'Tech' },
  { symbol: 'NFLX', name: 'Netflix', market: 'US', sector: 'Tech' },
  { symbol: 'CRM', name: 'Salesforce', market: 'US', sector: 'Tech' },
  { symbol: 'ADBE', name: 'Adobe', market: 'US', sector: 'Tech' },
  // ── US Financials / ETFs ─────────────────────────────────────────────────────
  { symbol: 'JPM', name: 'JPMorgan Chase', market: 'US', sector: 'Banking' },
  { symbol: 'SPY', name: 'S&P 500 ETF (SPDR)', market: 'US', sector: 'ETF' },
  { symbol: 'QQQ', name: 'Nasdaq 100 ETF (Invesco)', market: 'US', sector: 'ETF' },
  // ── Crypto ───────────────────────────────────────────────────────────────────
  { symbol: 'BTC-USD', name: 'Bitcoin', market: 'Crypto', sector: 'Crypto' },
  { symbol: 'ETH-USD', name: 'Ethereum', market: 'Crypto', sector: 'Crypto' },

  // ── NSE — Nifty Next 50 additions ────────────────────────────────────────────
  { symbol: 'ADANIENT.NS', name: 'Adani Enterprises', market: 'India', sector: 'Energy' },
  { symbol: 'ADANIGREEN.NS', name: 'Adani Green Energy', market: 'India', sector: 'Power' },
  { symbol: 'ADANIPOWER.NS', name: 'Adani Power', market: 'India', sector: 'Power' },
  { symbol: 'ATGL.NS', name: 'Adani Total Gas', market: 'India', sector: 'Energy' },
  { symbol: 'ABB.NS', name: 'ABB India', market: 'India', sector: 'Engineering' },
  { symbol: 'ACC.NS', name: 'ACC Cement', market: 'India', sector: 'Cement' },
  { symbol: 'AUROPHARMA.NS', name: 'Aurobindo Pharma', market: 'India', sector: 'Pharma' },
  { symbol: 'BANDHANBNK.NS', name: 'Bandhan Bank', market: 'India', sector: 'Banking' },
  { symbol: 'BERGEPAINT.NS', name: 'Berger Paints', market: 'India', sector: 'Paints' },
  { symbol: 'CHOLAFIN.NS', name: 'Cholamandalam Finance', market: 'India', sector: 'NBFC' },
  { symbol: 'DABUR.NS', name: 'Dabur India', market: 'India', sector: 'FMCG' },
  { symbol: 'DLF.NS', name: 'DLF', market: 'India', sector: 'Realty' },
  { symbol: 'GODREJCP.NS', name: 'Godrej Consumer Products', market: 'India', sector: 'FMCG' },
  { symbol: 'GODREJPROP.NS', name: 'Godrej Properties', market: 'India', sector: 'Realty' },
  { symbol: 'HAVELLS.NS', name: 'Havells India', market: 'India', sector: 'Electronics' },
  {
    symbol: 'ICICIPRULI.NS',
    name: 'ICICI Prudential Life Insurance',
    market: 'India',
    sector: 'Insurance',
  },
  { symbol: 'IDFCFIRSTB.NS', name: 'IDFC First Bank', market: 'India', sector: 'Banking' },
  { symbol: 'IOC.NS', name: 'Indian Oil Corporation', market: 'India', sector: 'Energy' },
  { symbol: 'LTIM.NS', name: 'LTIMindtree', market: 'India', sector: 'IT' },
  { symbol: 'LTTS.NS', name: 'L&T Technology Services', market: 'India', sector: 'IT' },
  { symbol: 'LUPIN.NS', name: 'Lupin', market: 'India', sector: 'Pharma' },
  { symbol: 'MAXHEALTH.NS', name: 'Max Healthcare', market: 'India', sector: 'Healthcare' },
  { symbol: 'MARICO.NS', name: 'Marico', market: 'India', sector: 'FMCG' },
  { symbol: 'MRF.NS', name: 'MRF', market: 'India', sector: 'Auto' },
  { symbol: 'NAUKRI.NS', name: 'Info Edge (Naukri)', market: 'India', sector: 'Tech' },
  { symbol: 'NMDC.NS', name: 'NMDC', market: 'India', sector: 'Mining' },
  { symbol: 'OFSS.NS', name: 'Oracle Financial Services', market: 'India', sector: 'IT' },
  { symbol: 'PAGEIND.NS', name: 'Page Industries', market: 'India', sector: 'Consumer' },
  { symbol: 'PERSISTENT.NS', name: 'Persistent Systems', market: 'India', sector: 'IT' },
  { symbol: 'PETRONET.NS', name: 'Petronet LNG', market: 'India', sector: 'Energy' },
  { symbol: 'PIIND.NS', name: 'PI Industries', market: 'India', sector: 'Chemical' },
  { symbol: 'POLYCAB.NS', name: 'Polycab India', market: 'India', sector: 'Electronics' },
  { symbol: 'SAIL.NS', name: 'SAIL', market: 'India', sector: 'Metals' },
  { symbol: 'SIEMENS.NS', name: 'Siemens India', market: 'India', sector: 'Engineering' },
  { symbol: 'TORNTPHARM.NS', name: 'Torrent Pharmaceuticals', market: 'India', sector: 'Pharma' },
  { symbol: 'TVSMOTOR.NS', name: 'TVS Motor Company', market: 'India', sector: 'Auto' },
  { symbol: 'UPL.NS', name: 'UPL', market: 'India', sector: 'Chemical' },
  { symbol: 'VEDL.NS', name: 'Vedanta', market: 'India', sector: 'Metals' },
  { symbol: 'ZYDUSLIFE.NS', name: 'Zydus Lifesciences', market: 'India', sector: 'Pharma' },
  { symbol: 'MOTHERSON.NS', name: 'Samvardhana Motherson', market: 'India', sector: 'Auto' },
  { symbol: 'INDIANB.NS', name: 'Indian Bank', market: 'India', sector: 'Banking' },
  { symbol: 'UNIONBANK.NS', name: 'Union Bank of India', market: 'India', sector: 'Banking' },
  { symbol: 'FEDERALBNK.NS', name: 'Federal Bank', market: 'India', sector: 'Banking' },
  { symbol: 'KALYANKJIL.NS', name: 'Kalyan Jewellers', market: 'India', sector: 'Consumer' },
  { symbol: 'OBEROIRLTY.NS', name: 'Oberoi Realty', market: 'India', sector: 'Realty' },
  { symbol: 'PHOENIX.NS', name: 'Phoenix Mills', market: 'India', sector: 'Realty' },
  { symbol: 'PRESTIGE.NS', name: 'Prestige Estates', market: 'India', sector: 'Realty' },
  { symbol: 'CROMPTON.NS', name: 'Crompton Greaves', market: 'India', sector: 'Electronics' },
  { symbol: 'VOLTAS.NS', name: 'Voltas', market: 'India', sector: 'Electronics' },

  // ── NSE — Popular Midcap & Smallcap ─────────────────────────────────────────
  { symbol: 'KPITTECH.NS', name: 'KPIT Technologies', market: 'India', sector: 'IT' },
  { symbol: 'COFORGE.NS', name: 'Coforge', market: 'India', sector: 'IT' },
  { symbol: 'MPHASIS.NS', name: 'Mphasis', market: 'India', sector: 'IT' },
  { symbol: 'HAPPSTMNDS.NS', name: 'Happiest Minds Technologies', market: 'India', sector: 'IT' },
  { symbol: 'CYIENT.NS', name: 'Cyient', market: 'India', sector: 'IT' },
  { symbol: 'TANLA.NS', name: 'Tanla Platforms', market: 'India', sector: 'Tech' },
  { symbol: 'ROUTE.NS', name: 'Route Mobile', market: 'India', sector: 'Tech' },
  { symbol: 'LATENTVIEW.NS', name: 'LatentView Analytics', market: 'India', sector: 'IT' },
  { symbol: 'TATAELXSI.NS', name: 'Tata Elxsi', market: 'India', sector: 'IT' },
  { symbol: 'SONACOMS.NS', name: 'Sona BLW Precision', market: 'India', sector: 'Auto' },
  { symbol: 'CAMPUS.NS', name: 'Campus Activewear', market: 'India', sector: 'Consumer' },
  { symbol: 'UNOMINDA.NS', name: 'UNO Minda', market: 'India', sector: 'Auto' },
  { symbol: 'ENDURANCE.NS', name: 'Endurance Technologies', market: 'India', sector: 'Auto' },
  { symbol: 'BALKRISIND.NS', name: 'Balkrishna Industries', market: 'India', sector: 'Auto' },
  { symbol: 'SPARC.NS', name: 'Sun Pharma Advanced', market: 'India', sector: 'Pharma' },
  { symbol: 'LAURUSLABS.NS', name: 'Laurus Labs', market: 'India', sector: 'Pharma' },
  { symbol: 'ALKEM.NS', name: 'Alkem Laboratories', market: 'India', sector: 'Pharma' },
  { symbol: 'IPCA.NS', name: 'IPCA Laboratories', market: 'India', sector: 'Pharma' },
  { symbol: 'NATCOPHARM.NS', name: 'Natco Pharma', market: 'India', sector: 'Pharma' },
  { symbol: 'GRANULES.NS', name: 'Granules India', market: 'India', sector: 'Pharma' },
  { symbol: 'LINDEINDIA.NS', name: 'Linde India', market: 'India', sector: 'Chemical' },
  { symbol: 'SRF.NS', name: 'SRF', market: 'India', sector: 'Chemical' },
  { symbol: 'AAVAS.NS', name: 'Aavas Financiers', market: 'India', sector: 'Finance' },
  { symbol: 'HOMEFIRST.NS', name: 'Home First Finance', market: 'India', sector: 'Finance' },
  { symbol: 'CREDITACC.NS', name: 'CreditAccess Grameen', market: 'India', sector: 'Finance' },
  { symbol: 'IIFL.NS', name: 'IIFL Finance', market: 'India', sector: 'Finance' },
  { symbol: 'MANAPPURAM.NS', name: 'Manappuram Finance', market: 'India', sector: 'Finance' },
  {
    symbol: 'CHOLAHLDNG.NS',
    name: 'Cholamandalam Investment',
    market: 'India',
    sector: 'Finance',
  },
  { symbol: 'CAMS.NS', name: 'CAMS', market: 'India', sector: 'Finance' },
  { symbol: 'ANGELONE.NS', name: 'Angel One', market: 'India', sector: 'Finance' },
  { symbol: 'CDSL.NS', name: 'CDSL', market: 'India', sector: 'Finance' },
  { symbol: 'BSE.NS', name: 'BSE (Exchange)', market: 'India', sector: 'Finance' },
  { symbol: 'MCX.NS', name: 'MCX (Exchange)', market: 'India', sector: 'Finance' },
  { symbol: 'NAVINFLUOR.NS', name: 'Navin Fluorine', market: 'India', sector: 'Chemical' },
  { symbol: 'CLEAN.NS', name: 'Clean Science Technology', market: 'India', sector: 'Chemical' },
  { symbol: 'TATAPOWER.NS', name: 'Tata Power', market: 'India', sector: 'Power' },
  { symbol: 'TORNTPOWER.NS', name: 'Torrent Power', market: 'India', sector: 'Power' },
  { symbol: 'CESC.NS', name: 'CESC', market: 'India', sector: 'Power' },
  { symbol: 'IGL.NS', name: 'Indraprastha Gas', market: 'India', sector: 'Energy' },
  { symbol: 'MGL.NS', name: 'Mahanagar Gas', market: 'India', sector: 'Energy' },
  { symbol: 'CONCOR.NS', name: 'Container Corporation', market: 'India', sector: 'Logistics' },
  { symbol: 'BLUEDART.NS', name: 'Blue Dart Express', market: 'India', sector: 'Logistics' },
  { symbol: 'MAHINDCIE.NS', name: 'Mahindra CIE Automotive', market: 'India', sector: 'Auto' },
  { symbol: 'TIINDIA.NS', name: 'Tube Investments', market: 'India', sector: 'Engineering' },
  { symbol: 'APARINDS.NS', name: 'Apar Industries', market: 'India', sector: 'Engineering' },
  { symbol: 'ELGIEQUIP.NS', name: 'Elgi Equipments', market: 'India', sector: 'Engineering' },
  { symbol: 'GRINDWELL.NS', name: 'Grindwell Norton', market: 'India', sector: 'Engineering' },
  { symbol: 'AIAENG.NS', name: 'AIA Engineering', market: 'India', sector: 'Engineering' },
  { symbol: 'ASTRAL.NS', name: 'Astral', market: 'India', sector: 'Plumbing' },
  { symbol: 'SUPREMEIND.NS', name: 'Supreme Industries', market: 'India', sector: 'Plastics' },
  { symbol: 'HINDPETRO.NS', name: 'HPCL', market: 'India', sector: 'Energy' },
  { symbol: 'MRPL.NS', name: 'Mangalore Refinery', market: 'India', sector: 'Energy' },
  { symbol: 'BANKINDIA.NS', name: 'Bank of India', market: 'India', sector: 'Banking' },
  { symbol: 'MAHABANK.NS', name: 'Bank of Maharashtra', market: 'India', sector: 'Banking' },
  { symbol: 'IDBI.NS', name: 'IDBI Bank', market: 'India', sector: 'Banking' },
  { symbol: 'RBLBANK.NS', name: 'RBL Bank', market: 'India', sector: 'Banking' },
  {
    symbol: 'EQUITASBNK.NS',
    name: 'Equitas Small Finance Bank',
    market: 'India',
    sector: 'Banking',
  },
  { symbol: 'SURYAROSNI.NS', name: 'Surya Roshni', market: 'India', sector: 'Consumer' },
  { symbol: 'VGUARD.NS', name: 'V-Guard Industries', market: 'India', sector: 'Electronics' },
  { symbol: 'ORIENTELEC.NS', name: 'Orient Electric', market: 'India', sector: 'Electronics' },
  { symbol: 'DIXON.NS', name: 'Dixon Technologies', market: 'India', sector: 'Electronics' },
  { symbol: 'AMBER.NS', name: 'Amber Enterprises', market: 'India', sector: 'Electronics' },
  { symbol: 'SULA.NS', name: 'Sula Vineyards', market: 'India', sector: 'Consumer' },
  { symbol: 'DEVYANI.NS', name: 'Devyani International', market: 'India', sector: 'Consumer' },
  { symbol: 'JUBLFOOD.NS', name: 'Jubilant FoodWorks', market: 'India', sector: 'Consumer' },
  { symbol: 'WESTLIFE.NS', name: 'Westlife Foodworld', market: 'India', sector: 'Consumer' },

  // ── BSE — Additional popular stocks (.BO) ────────────────────────────────────
  { symbol: 'ADANIENT.BO', name: 'Adani Enterprises (BSE)', market: 'India', sector: 'Energy' },
  { symbol: 'ADANIGREEN.BO', name: 'Adani Green Energy (BSE)', market: 'India', sector: 'Power' },
  { symbol: 'DLF.BO', name: 'DLF (BSE)', market: 'India', sector: 'Realty' },
  { symbol: 'HAVELLS.BO', name: 'Havells India (BSE)', market: 'India', sector: 'Electronics' },
  { symbol: 'IOC.BO', name: 'Indian Oil (BSE)', market: 'India', sector: 'Energy' },
  { symbol: 'LTIM.BO', name: 'LTIMindtree (BSE)', market: 'India', sector: 'IT' },
  { symbol: 'LUPIN.BO', name: 'Lupin (BSE)', market: 'India', sector: 'Pharma' },
  { symbol: 'TVSMOTOR.BO', name: 'TVS Motor (BSE)', market: 'India', sector: 'Auto' },
  { symbol: 'SIEMENS.BO', name: 'Siemens India (BSE)', market: 'India', sector: 'Engineering' },
  { symbol: 'TORNTPHARM.BO', name: 'Torrent Pharma (BSE)', market: 'India', sector: 'Pharma' },
  { symbol: 'VEDL.BO', name: 'Vedanta (BSE)', market: 'India', sector: 'Metals' },
  { symbol: 'SAIL.BO', name: 'SAIL (BSE)', market: 'India', sector: 'Metals' },
  { symbol: 'DABUR.BO', name: 'Dabur India (BSE)', market: 'India', sector: 'FMCG' },
  { symbol: 'GODREJCP.BO', name: 'Godrej Consumer (BSE)', market: 'India', sector: 'FMCG' },
  { symbol: 'MARICO.BO', name: 'Marico (BSE)', market: 'India', sector: 'FMCG' },

  // ── US Stocks — Finance & Banking ────────────────────────────────────────────
  { symbol: 'BAC', name: 'Bank of America', market: 'US', sector: 'Banking' },
  { symbol: 'GS', name: 'Goldman Sachs', market: 'US', sector: 'Banking' },
  { symbol: 'MS', name: 'Morgan Stanley', market: 'US', sector: 'Banking' },
  { symbol: 'WFC', name: 'Wells Fargo', market: 'US', sector: 'Banking' },
  { symbol: 'C', name: 'Citigroup', market: 'US', sector: 'Banking' },
  { symbol: 'V', name: 'Visa', market: 'US', sector: 'Finance' },
  { symbol: 'MA', name: 'Mastercard', market: 'US', sector: 'Finance' },
  { symbol: 'AXP', name: 'American Express', market: 'US', sector: 'Finance' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway B', market: 'US', sector: 'Finance' },
  { symbol: 'BLK', name: 'BlackRock', market: 'US', sector: 'Finance' },

  // ── US Stocks — Tech (expanded) ──────────────────────────────────────────────
  { symbol: 'INTC', name: 'Intel', market: 'US', sector: 'Tech' },
  { symbol: 'QCOM', name: 'Qualcomm', market: 'US', sector: 'Tech' },
  { symbol: 'ORCL', name: 'Oracle', market: 'US', sector: 'Tech' },
  { symbol: 'IBM', name: 'IBM', market: 'US', sector: 'Tech' },
  { symbol: 'NOW', name: 'ServiceNow', market: 'US', sector: 'Tech' },
  { symbol: 'SNOW', name: 'Snowflake', market: 'US', sector: 'Tech' },
  { symbol: 'PLTR', name: 'Palantir', market: 'US', sector: 'Tech' },
  { symbol: 'UBER', name: 'Uber', market: 'US', sector: 'Tech' },
  { symbol: 'ABNB', name: 'Airbnb', market: 'US', sector: 'Tech' },
  { symbol: 'SHOP', name: 'Shopify', market: 'US', sector: 'Tech' },
  { symbol: 'PYPL', name: 'PayPal', market: 'US', sector: 'Tech' },
  { symbol: 'SQ', name: 'Block (Square)', market: 'US', sector: 'Tech' },
  { symbol: 'COIN', name: 'Coinbase', market: 'US', sector: 'Tech' },
  { symbol: 'RBLX', name: 'Roblox', market: 'US', sector: 'Tech' },
  { symbol: 'HOOD', name: 'Robinhood', market: 'US', sector: 'Tech' },

  // ── US Stocks — Healthcare ───────────────────────────────────────────────────
  { symbol: 'JNJ', name: 'Johnson & Johnson', market: 'US', sector: 'Pharma' },
  { symbol: 'PFE', name: 'Pfizer', market: 'US', sector: 'Pharma' },
  { symbol: 'MRK', name: 'Merck', market: 'US', sector: 'Pharma' },
  { symbol: 'ABBV', name: 'AbbVie', market: 'US', sector: 'Pharma' },
  { symbol: 'LLY', name: 'Eli Lilly', market: 'US', sector: 'Pharma' },
  { symbol: 'UNH', name: 'UnitedHealth Group', market: 'US', sector: 'Healthcare' },
  { symbol: 'CVS', name: 'CVS Health', market: 'US', sector: 'Healthcare' },
  { symbol: 'MDT', name: 'Medtronic', market: 'US', sector: 'Healthcare' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', market: 'US', sector: 'Pharma' },
  { symbol: 'AMGN', name: 'Amgen', market: 'US', sector: 'Biotech' },
  { symbol: 'GILD', name: 'Gilead Sciences', market: 'US', sector: 'Biotech' },
  { symbol: 'BIIB', name: 'Biogen', market: 'US', sector: 'Biotech' },

  // ── US Stocks — Energy ───────────────────────────────────────────────────────
  { symbol: 'XOM', name: 'ExxonMobil', market: 'US', sector: 'Energy' },
  { symbol: 'CVX', name: 'Chevron', market: 'US', sector: 'Energy' },
  { symbol: 'COP', name: 'ConocoPhillips', market: 'US', sector: 'Energy' },
  { symbol: 'SLB', name: 'SLB (Schlumberger)', market: 'US', sector: 'Energy' },
  { symbol: 'EOG', name: 'EOG Resources', market: 'US', sector: 'Energy' },

  // ── US Stocks — Consumer ─────────────────────────────────────────────────────
  { symbol: 'WMT', name: 'Walmart', market: 'US', sector: 'Retail' },
  { symbol: 'COST', name: 'Costco', market: 'US', sector: 'Retail' },
  { symbol: 'HD', name: 'Home Depot', market: 'US', sector: 'Retail' },
  { symbol: 'MCD', name: "McDonald's", market: 'US', sector: 'Consumer' },
  { symbol: 'KO', name: 'Coca-Cola', market: 'US', sector: 'Consumer' },
  { symbol: 'PEP', name: 'PepsiCo', market: 'US', sector: 'Consumer' },
  { symbol: 'PG', name: 'Procter & Gamble', market: 'US', sector: 'Consumer' },
  { symbol: 'NKE', name: 'Nike', market: 'US', sector: 'Consumer' },
  { symbol: 'SBUX', name: 'Starbucks', market: 'US', sector: 'Consumer' },
  { symbol: 'TGT', name: 'Target', market: 'US', sector: 'Retail' },

  // ── US ETFs (expanded) ───────────────────────────────────────────────────────
  { symbol: 'IWM', name: 'Russell 2000 ETF', market: 'US', sector: 'ETF' },
  { symbol: 'DIA', name: 'Dow Jones ETF', market: 'US', sector: 'ETF' },
  { symbol: 'GLD', name: 'Gold ETF (SPDR)', market: 'US', sector: 'Commodity ETF' },
  { symbol: 'SLV', name: 'Silver ETF', market: 'US', sector: 'Commodity ETF' },
  { symbol: 'TLT', name: '20+ Year Treasury Bond ETF', market: 'US', sector: 'ETF' },
  { symbol: 'VTI', name: 'Vanguard Total Market ETF', market: 'US', sector: 'ETF' },
  { symbol: 'VOO', name: 'Vanguard S&P 500 ETF', market: 'US', sector: 'ETF' },
  { symbol: 'ARKK', name: 'ARK Innovation ETF', market: 'US', sector: 'ETF' },
  { symbol: 'XLF', name: 'Financial Select Sector ETF', market: 'US', sector: 'ETF' },
  { symbol: 'XLE', name: 'Energy Select Sector ETF', market: 'US', sector: 'ETF' },
  { symbol: 'XLK', name: 'Technology Select Sector ETF', market: 'US', sector: 'ETF' },
];

/**
 * Search the index by query string.
 * Matches on symbol prefix first, then name substring, then sector.
 * Returns up to `limit` results.
 */
export function searchSymbols(query, limit = 8) {
  if (!query || query.length < 1) return [];
  const q = query.toLowerCase().trim();

  const symbolPrefix = [];
  const nameMatch = [];
  const seen = new Set();

  for (const item of SYMBOL_INDEX) {
    const bare = item.symbol.toLowerCase().replace(/\.(ns|bo|l|de|pa|t|ax|to)$/, '');
    const sym = item.symbol.toLowerCase();
    const name = item.name.toLowerCase();
    const sector = item.sector.toLowerCase();

    const bySymbol = sym.startsWith(q) || bare.startsWith(q);
    const byName = name.includes(q) || sector.includes(q);

    if (!bySymbol && !byName) continue;
    if (seen.has(item.symbol)) continue;
    seen.add(item.symbol);

    if (bySymbol) {
      symbolPrefix.push(item);
    } else {
      nameMatch.push(item);
    }
  }

  return [...symbolPrefix, ...nameMatch].slice(0, limit);
}
